<?php /* Reports index view */
?>
<style>
  .exp-grid { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 14px; }
  .exp-tile { display: flex; align-items: center; gap: 13px; padding: 17px 18px; border: 1px solid var(--border); border-radius: var(--radius); background: var(--bg-elev); transition: all var(--transition); text-decoration: none; color: inherit; min-width: 0; }
  .exp-tile:hover { border-color: transparent; background: var(--glass-nav-hover); backdrop-filter: blur(32px) saturate(180%); -webkit-backdrop-filter: blur(32px) saturate(180%); transform: translateY(-1px); box-shadow: 0 0 0 1px rgba(255,255,255,.15), inset 0 1px 1px rgba(255,255,255,.2), 0 4px 16px rgba(0,0,0,.06); }
  .exp-ic { width: 42px; height: 42px; border-radius: 11px; background: var(--accent-soft); display: flex; align-items: center; justify-content: center; flex-shrink: 0; }
  .exp-ic svg { width: 20px; height: 20px; color: var(--accent); }
  .exp-tile b { font-size: 13.5px; }
  .exp-tile .tiny { margin-top: 2px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
  @media (max-width: 860px) { .exp-grid { grid-template-columns: 1fr; } }
</style>

<div class="page-head">
  <div>
    <h1><?= icon('trend-up') ?> Reports</h1>
    <p class="sub">Your generated reports and quick exports</p>
    <?php if (!empty($school_name)): ?>
      <p class="sub" style="margin-top:8px"><span class="badge badge-info" style="padding:5px 12px"><?= icon('school') ?> Your school: <?= e($school_name) ?> — exports are limited to your school</span></p>
    <?php endif; ?>
  </div>
</div>

<div class="card" style="margin-bottom:18px">
  <h3 class="card-title" style="margin-top:0"><?= icon('bolt') ?> Quick CSV exports</h3>
  <div class="exp-grid">
    <a class="exp-tile" href="<?= e(url('reports/export&type=courses')) ?>">
      <span class="exp-ic"><?= icon('books') ?></span>
      <span><b>Courses CSV</b><p class="tiny faint">All courses in your school</p></span>
    </a>
    <a class="exp-tile" href="<?= e(url('reports/export&type=users')) ?>">
      <span class="exp-ic"><?= icon('users') ?></span>
      <span><b>Users CSV</b><p class="tiny faint">Students, teachers and staff</p></span>
    </a>
    <a class="exp-tile" href="<?= e(url('reports/export&type=exams')) ?>">
      <span class="exp-ic"><?= icon('note') ?></span>
      <span><b>Exams CSV</b><p class="tiny faint">Exams and their questions</p></span>
    </a>
    <a class="exp-tile" href="<?= e(url('reports/export&type=courses&format=pdf')) ?>">
      <span class="exp-ic" style="background:var(--danger-soft)"><?= icon('file') ?></span>
      <span><b>Courses PDF</b><p class="tiny faint">Print-ready course report</p></span>
    </a>
    <a class="exp-tile" href="<?= e(url('reports/export&type=users&format=pdf')) ?>">
      <span class="exp-ic" style="background:var(--danger-soft)"><?= icon('file') ?></span>
      <span><b>Users PDF</b><p class="tiny faint">Print-ready user report</p></span>
    </a>
    <a class="exp-tile" href="<?= e(url('reports/export&type=exams&format=pdf')) ?>">
      <span class="exp-ic" style="background:var(--danger-soft)"><?= icon('file') ?></span>
      <span><b>Exams PDF</b><p class="tiny faint">Print-ready exam report</p></span>
    </a>
  </div>
</div>

<div class="card">
  <h3 class="card-title" style="margin-top:0"><?= icon('folder') ?> Generated reports</h3>
  <?php if (!$reports): ?>
    <div class="empty-state">
      <div class="empty-ic"><?= icon('folder') ?></div>
      <h3>No reports generated yet</h3>
      <p class="small">Downloaded report files will be listed here once generated by your school. Use the quick CSV exports above to get data right away.</p>
    </div>
  <?php else: ?>
    <table class="table">
      <thead><tr><th>Title</th><th>Type</th><th>School</th><th>Format</th><th>Created</th><th></th></tr></thead>
      <tbody>
        <?php foreach ($reports as $r): ?>
          <tr>
            <td><b class="small"><?= e($r['title']) ?></b></td>
            <td><span class="badge badge-muted"><?= e($r['type']) ?></span></td>
            <td class="small"><?= e($r['school_name']) ?></td>
            <td class="small"><?= e($r['format']) ?></td>
            <td class="small faint"><?= e(date('M j, H:i', strtotime($r['created_at']))) ?></td>
            <td><a class="btn btn-sm" href="<?= e(url('reports/index&download=' . $r['id'])) ?>"><?= icon('download') ?> Download</a></td>
          </tr>
        <?php endforeach; ?>
      </tbody>
    </table>
  <?php endif; ?>
</div>
